### ISSUE TITLE
单击桌面文件后，文件名字体变大

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#102]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、左键桌面上所有文件或程序

预期结果：显示正常

实际结果：文件名的字体变大

**Comment by Yue-Lan** [comment]
57a44e7b343b26494dba650296fd754f0efd8397 修复了这个问题，另外桌面不再尝试根据当前图标大小调整字体大小了

**Comment by 1216338727aa** [comment]
20200320版本测试通过
