### ISSUE TITLE
列表模式下，点击空白处不能使用全选快捷键

### ISSUE THREAD

**Issue by moshengrenzenme** [ukui/peony#103]

**Comment by Yue-Lan** [comment]
Is this issue related with pr(#94)?

**Comment by dou-y** [comment]
yes, I think it is related. Because call method clearFocus(), then short cut key will not work. Qtwidget must enable focus setting in order to get the keyboard input focus.

**Comment by MeganHemh** [comment]
兰悦已经合并dou-y的提交，验证已经解决，本周新集成版本可进行验证。

**Comment by 1216338727aa** [comment]
20200320版本测试通过
