### ISSUE TITLE
在桌面选中一个文件后右键菜单显示错误

### ISSUE THREAD

**Issue by moshengrenzenme** [ukui/peony#104]
在桌面选中一个文件后在其他的任意图标上右键，右键菜单菜单显示的依旧是刚开始选中的文件菜单
![2020-03-14 23-31-00屏幕截图](https://user-images.githubusercontent.com/33083187/76685085-e643ba00-664b-11ea-83ad-ba85a0c22108.png)

**Comment by Yue-Lan** [comment]
I will take over this issue.

**Comment by 1216338727aa** [comment]
20200320版本测试通过
