### ISSUE TITLE
桌面上kylin文件夹可复制粘贴

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#105]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、全选桌面上计算机、回收站、个人文件夹
2、ctrl+c复制后，ctrl+v到桌面

预期结果：无法复制粘贴

实际结果：在弹出的窗口中，选择覆盖后，kylin主文件夹成功复制至桌面

**Comment by Yue-Lan** [comment]
我认为没有足够的理由禁止用户这样做。。。

**Comment by MeganHemh** [comment]
个人主目录已经过滤掉复制/剪切/删除/重命名操作。本周集成的新版本可进行验证。

**Comment by 1216338727aa** [comment]
20200320版本测试通过
