### ISSUE TITLE
文件管理器中，右键标记颜色未显示

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#106]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开文件管理器窗口
2、选中一个文件后，右键点击添加标记

预期结果：显示正常

实际结果：下拉菜单中，显示的颜色示例均为空

**Comment by MeganHemh** [comment]
The latest version has added this function.

**Comment by liumin0322** [comment]
20200818 test passed
