### ISSUE TITLE
文件管理器中，标记功能未生效

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#107]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开文件管理器窗口
2、选中一个文件后，右键点击添加标记
3、选择红色

预期结果：查看该文件或文件夹，标记颜色生效

实际结果：未生效

**Comment by Yue-Lan** [comment]
目前还没有来得及处理标记相关的装饰功能，需要等底层的一些标记和筛选机制等问题完全解决之后再继续推进UI层的效果展示

**Comment by Liang-zy** [comment]
20.04.1 test passed
