### ISSUE TITLE
在桌面复制一个文件后，右键可持续粘贴

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#108]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、在桌面选中一个文件复制
2、在桌面空白处点击右键菜单粘贴
3、粘贴完成后，继续点击右键菜单

预期结果：粘贴一次完成后，无法再粘贴

实际结果：右键菜单可持续点击粘贴

**Comment by xiaodongliu-nudt** [comment]
@Yue-Lan @MeganHemh window和Mac中也可以持续粘贴，是否为bug？ @liumin0322

**Comment by Yue-Lan** [comment]
之前检测到高频率粘贴导致概率崩溃的问题，这里没有表述出来，这里@liumin0322应该是希望提供一种更稳定的方式，我会尝试降低触发频率，并且解决概率崩溃的问题。

**Comment by MeganHemh** [comment]
最新版本已经实现持续粘贴功能。

**Comment by 1216338727aa** [comment]
20200611 test passed   When copying and pasting with high frequency, prompt information is added.
