### ISSUE TITLE
关于中的公司名称应更新

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#109]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开文件管理器
2、在选项中，选择关于

预期结果：公司名称应为麒麟软件有限公司

实际结果：

**Comment by xiaodongliu-nudt** [comment]
Copyright应该有统一的写法， 可以跟@handsome-feng 确认下

**Comment by Yue-Lan** [comment]
Confirmed.

**Comment by MeganHemh** [comment]
已经修改提交，本周集成的新版本可进行验证。

**Comment by 1216338727aa** [comment]
20200320版本测试通过
