### ISSUE TITLE
右键选择在新窗口中打开，文件管理器崩溃

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#110]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开文件管理器
2、在空白处右键，并选择在新窗口中打开

预期结果：成功打开新窗口

实际结果：文件管理器崩溃

**Comment by Yue-Lan** [comment]
Fixed with commit 80fdcc395daa70c3f7ca9f9f8aac992d7b45054b.

**Comment by 1216338727aa** [comment]
20200320版本测试通过
