### ISSUE TITLE
搜索框中，无法输入中文

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#116]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、点击搜索按钮
2、在搜索框中切换为中文输入

预期结果：可成功输入中文

实际结果：无法输入中文

**Comment by MeganHemh** [comment]
搜狗输入法无法输入中文，但是系统自带的输入法可以输入中文，需要查一下原因。

**Comment by MeganHemh** [comment]
1. 测试机上是用iso安装的，必现，我本机是直升上去的版本，自带的拼音输入法以及安装谷歌输入法都表现正常，所以目前不好调试和排查原因。
2. 目前想安装搜狗输入法看能否在本机复现问题，但是安装失败，无法修复失败报错。

**Comment by MeganHemh** [comment]
第一次可以输入，后面直接无法切换中文输入，是历史记录下拉列表导致。
修复代码已经提交：989f0552e966ad538e5b04e07df77310fa6b2d1e
下个新版本可进行验证。

**Comment by 1216338727aa** [comment]
20200611 test passed
