### ISSUE TITLE
详细信息中的内容不支持换行，导致窗口显示异常

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#117]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开文件管理器窗口，点击详细信息按钮
2、选择一个文件名较长的文件

预期结果：详细信息窗口中内容会调整

实际结果：详细信息中的内容不支持换行，导致窗口显示异常

**Comment by Yue-Lan** [comment]
I will take over this issue.

**Comment by liumin0322** [comment]
20200321版本测试通过。
