### ISSUE TITLE
文件管理器的地址栏，未显示层级路径

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#120]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开图片文件夹，并创建新文件夹，进入新建文件夹中

预期结果：地址栏中应显示：kylin->图片->新建文件夹

实际结果：仅显示：新建文件夹

**Comment by Yue-Lan** [comment]
this bug has been resolved by commit 223cbc55cb43862e5843d9ac359d1df115524a8a.

**Comment by 1216338727aa** [comment]
20200320版本测试通过
