### ISSUE TITLE
右键排序偏好设置后，勾选框仍为空

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#122]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、文件管理器中，空白处右键点击
2、选择排序偏好，对“文件夹优先”、“中文优先”、“显示隐藏文件”进行设置

预期结果：设置后，勾选框实时更新

实际结果：设置生效后，勾选框未改变

**Comment by Yue-Lan** [comment]
已确认，这是迁移留下的问题，麻烦@MeganHemh检查一下相关接口的实现

**Comment by MeganHemh** [comment]
下周新版本可验证，已修改提交。
