### ISSUE TITLE
右键排序偏好设置后，无法取消

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#123]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开文件管理器，在空白处右键
2、选择排序偏好-显示隐藏文件，成功生效，显示隐藏文件
3、再次设置，取消显示隐藏文件

预期结果：可成功取消显示隐藏文件

实际结果：取消无效

**Comment by Yue-Lan** [comment]
duplicate with #122

**Comment by MeganHemh** [comment]
下周新版本可验证，已修改提交。

**Comment by 1216338727aa** [comment]
20200320版本测试通过
