### ISSUE TITLE
选项菜单中，高级搜索点击无效

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#124]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、点击选项按钮，弹出下拉菜单栏
2、点击高级搜索

预期结果：弹出高级搜索功能

实际结果：无响应

**Comment by MeganHemh** [comment]
高级搜索功能需要全新改版，预计有一周左右的开发工作量，这边工作计划是先把优先级高的bug修复掉，后续再做改版工作，是否需要先屏蔽入口？

**Comment by Yue-Lan** [comment]
可以，但是可能要考虑文件标记这一块的体现方式，也许目前可以通过点击labelview的item进行筛选？

**Comment by MeganHemh** [comment]
高级搜索功能需要进行新版改版，目前屏蔽了入口。目前颜色标签提供了分类筛选功能。

**Comment by 1216338727aa** [comment]
20200320版本测试通过
