### ISSUE TITLE
当文件夹名称较长时，导致关闭按钮无法显示

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#127]
![2020-03-16 20-22-09屏幕截图](https://user-images.githubusercontent.com/48200161/76758091-ef579700-67c3-11ea-8857-b9a143cc4315.png)

**Comment by Yue-Lan** [comment]
bffd30fbfd560ed5a225d98008108a11d412fc61 修复了这个问题

**Comment by 1216338727aa** [comment]
20200320版本测试通过
