### ISSUE TITLE
桌面移动文件时，发现两个文件图标重叠

### ISSUE THREAD

**Issue by 1216338727aa** [ukui/peony#128]
![a8c36dff8bb4a74a85aca95f0368c5f](https://user-images.githubusercontent.com/39893452/76760791-3e53fb00-67c9-11ea-8e12-c1c2efc69cec.jpg)

**Comment by Yue-Lan** [comment]
已确认，有概率发生这种问题，具体原因还没有分析到。。。

P.S:桌面图标的位置会被记录，目前刷新是不会改变堆叠文件的位置的，如果出现这种情况可以对桌面进行重新排序

**Comment by 1216338727aa** [comment]
20200618 test passed
