### ISSUE TITLE
回收站右键压缩失败

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#129]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、右键点击回收站，选择压缩
2、在弹出的窗口中输入文件名，点击创建

预期结果：无压缩选项，或压缩成功

实际结果：提示：将文件添加到归档文件时出现一个错误

**Comment by MeganHemh** [comment]
最新的已经修改为屏蔽压缩选项，本周集成到版本更新，下周可以验证。

**Comment by 1216338727aa** [comment]
20200320版本测试通过
