### ISSUE TITLE
链接的原始文件夹被删除后，打开链接文件夹，无任何提示

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#130]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开文件管理器，将桌面路径下的一个文件夹链接到桌面
2、删除原始文件夹
3、打开桌面的快捷方式

预期结果：提示原始文件被删除

实际结果：无任何提示信息，打开的为桌面文件夹

**Comment by Yue-Lan** [comment]
目前的路径跳转设计是首先进行跳转，然后自动尝试处理错误，对于完全非法路径会尝试返回上一级。。。在通常情况下我们并不希望有弹窗，比如进入一个未挂载的设备，文件管理器不会提示未挂载，而是自动挂载之后进入。

我不是特别想修改现有的路径跳转框架，因为我认为在双击之后进行预处理等待是不划算的，文件系统中大部分的文件都可以直接进入，只有极少部分的会出现错误，并且其中大约一半的错误还是可以根据返回的信息进行相应处理解决的。我会首先尝试对无法进行自动处理的跳转错误进行弹窗警告，但是得到的错误信息应该不会特别精细。

**Comment by MeganHemh** [comment]
最新版本已经有提示，可验证。

**Comment by 1216338727aa** [comment]
20200618 test faild

**Comment by MeganHemh** [comment]
最新版本已经OK.

**Comment by MeganHemh** [comment]
已添加删除无效链接提示，代码: 6e973a52d0bb636b8311e9621291a87171b5805b
下周新版本可验证。

**Comment by liumin0322** [comment]
test passed
