### ISSUE TITLE
kylin文件夹的右键删除操作，执行报错

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#131]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、右键点击桌面kylin文件夹
2、选择删除操作

预期结果：无删除选项，或可成功删除

实际结果：弹出文件操作错误弹窗：无法将文件/home/kylin移动到回收站：无效的参数

**Comment by MeganHemh** [comment]
已修改提交(819a5f94b5c140c40eb62d89e6bf9e391ed0c131), 个人帐号文件夹不允许复制/剪切/删除以及重命名操作。本周新集成版本可验证。

**Comment by 1216338727aa** [comment]
20200320版本测试通过
