### ISSUE TITLE
地址栏在点击其他位置之后还是可编辑模式

### ISSUE THREAD

**Issue by moshengrenzenme** [ukui/peony#133]
地址栏在点击其他位置之后还是可编辑模式
步骤：点击地址栏变成可编辑模式，然后点击其他的地方（地址栏之外的地方，但是不能是下边的文件内容）
预期结果：地址栏由可编辑模式变成导航模式
实际结果：仍旧是编辑模式

**Comment by MeganHemh** [comment]
没有新的选中目标的时候，焦点并不会切换走，需要确认这时候需要取消当前目标聚焦吗？

**Comment by moshengrenzenme** [comment]
> 没有新的选中目标的时候，焦点并不会切换走，需要确认这时候需要取消当前目标聚焦吗？

我还以为是写出bug了，如果是设计成这样的那应该是有设计的考量的

**Comment by liumin0322** [comment]
windows上也是如此

**Comment by vhtq18w** [comment]
dolphin 也是这样的
