### ISSUE TITLE
双屏显示，更换主屏，屏幕黑屏，桌面右键无反应

### ISSUE THREAD

**Issue by 1216338727aa** [ukui/peony#136]
版本：20.04LTS
iso：ubuntukylin-ukui3.0-20200313-amd64.iso
测试环境：联想启天M415-N000台式机

测试步骤：
1.接入两个显示器,HDMI和VGA,VGA为主屏
2.把HDMI设置成主屏

预期结果： 设置成功，显示正常
实际结果：VGA显示屏黑屏，在VGA屏幕桌面 鼠标右键无反应

**Comment by Yue-Lan** [comment]
> 版本：20.04LTS
> iso：ubuntukylin-ukui3.0-20200313-amd64.iso
> 测试环境：联想启天M415-N000台式机
> 
> 测试步骤：
> 1.接入两个显示器,HDMI和VGA,VGA为主屏
> 2.把HDMI设置成主屏
> 
> 预期结果： 设置成功，显示正常
> 实际结果：VGA显示屏黑屏，在VGA屏幕桌面 鼠标右键无反应

@1216338727aa ，这是迁移kwin引入的新问题，原来在ukwm下改变屏幕大小和位置的代码在kwin下无效了。。。

建议在切换窗口管理器，在ukwm下验证一下是否还存在相同lebel的问题，如果有我会优先修复那些和窗口管理器无关的问题。

**Comment by MeganHemh** [comment]
The development version is OK in both ukwm and k-win, Please check it in the new version of this week.

**Comment by liumin0322** [comment]
Tested pass in the 20200410 version
