### ISSUE TITLE
主机连接HMDI显示器，重启进入系统，插上VGA,VGA直接就是主屏幕，而且是黑屏，桌面无图标

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#140]

**Comment by Yue-Lan** [comment]
@liumin0322 , @1216338727aa  我想 8609ef1287c87bb76a68affdad6ed16e48d32fff 和 8609ef1287c87bb76a68affdad6ed16e48d32fff 应该已经修复了这个问题，请测试在下个版本测试这个issue以及其它相关标签的issue，然后补充详细的信息。

**Comment by 1216338727aa** [comment]
20200320版本此问题未解决，还是存在问题；重启进入系统插上VGA,，任务栏在VGA上，桌面图标在HDMI上，点击开始菜单，出现在HMDI上。VGA还是有黑屏现象。

**Comment by 1216338727aa** [comment]
20200328版本此问题未解决，还是存在问题；重启进入系统插上VGA,，任务栏在VGA上，桌面图标在HDMI上，点击开始菜单，出现在HMDI上。VGA还是有黑屏现象。

**Comment by MeganHemh** [comment]
The development version is OK, Please check it in the new version of this week.

**Comment by liumin0322** [comment]
Tested pass in the 20200410 version
