### ISSUE TITLE
通过终端执行peony .命令，打开窗口路径不正确

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#146]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200321-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开一个文件管理器窗口
2、打开终端，进入/usr/share/路径下，输入peony . 命令

预期结果：成功打开/usr/share窗口

实际结果：打开的窗口路径为/home

**Comment by MeganHemh** [comment]
已确认，多个窗口情况下会有问题。

**Comment by MeganHemh** [comment]
最新版本倚解决，可验证。

**Comment by 1216338727aa** [comment]
2020521 test failed

**Comment by MeganHemh** [comment]
@1216338727aa 2004最新版本测试还失败吗？我这边都没问题

**Comment by 1216338727aa** [comment]
> @ 1216338727aa 2004最新版本测试还失败吗？我这边都没问题

我这边更新到0521版本和0521iso安装的都有问题

**Comment by Yue-Lan** [comment]
这里没复现。。。这个问题很早以前就解决了，关联提交 a2aef517fc2784a38df17d652dedde3451e04608
