### ISSUE TITLE
通过终端执行peony .打开窗口，ctrl+z终止进程后，文件管理器崩溃

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#147]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200321-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、通过终端执行peony .打开窗口
2、键盘执行ctrl+z终止进程

预期结果：可成功关闭文件管理器

实际结果：文件管理器崩溃，无法操作

**Comment by MeganHemh** [comment]
ctrl+z是进程挂起命令，不是终止进程命令。
　(1) CTRL+Z挂起进程并放入后台
　(2) jobs 显示当前暂停的进程
　(3) bg %N 使第N个任务在后台运行(%前有空格)
　(4) fg %N 使第N个任务在前台运行
　默认bg,fg不带%N时表示对最后一个进程操作!

**Comment by MeganHemh** [comment]
想要退出进程请使用Ctrl +C,可正常退出。
