### ISSUE TITLE
麒麟助手创建桌面快捷方式，桌面图标显示不对

### ISSUE THREAD

**Issue by 1216338727aa** [ukui/peony#149]
版本：20.04LTS
iso：ubuntukylin-ukui3.0-20200320-amd64.iso
测试环境：联想兆芯E  CF4620Z笔记本
测试环境：联想启天M415-N000台式机
测试步骤：
1.开始菜单-麒麟助手
2.创建桌面快捷方式

预期结果： 创建快捷方式成功，图标应和开始菜单一致
实际结果： 图标和开始菜单中的不一致

**Comment by Yue-Lan** [comment]
麒麟助手的图标字段是kylin-assistant.png，其实一般只需要kylin-assistant就可以了。。。我会在桌面图标获取时增加一个判断

**Comment by MeganHemh** [comment]
目前表现已正常，属性图标也已经修改正常显示。

**Comment by 1216338727aa** [comment]
20200402版本测试通过
