### ISSUE TITLE
桌面右键选择“打开终端”，默认打开的文件路径是桌面

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#15]
Right-click on the desktop and select Open Terminal. The default file path is desktop.

（默认应是个人主目录）

**Comment by MeganHemh** [comment]
Ctrl+Alt+T 打开终端默认是个人主目录， 桌面右键打开为当前路径，应属于正常情况。

**Comment by Yue-Lan** [comment]
The desgining it is. won't fix.
