### ISSUE TITLE
桌面左键多选几个文件，右键只能操作一个

### ISSUE THREAD

**Issue by 1216338727aa** [ukui/peony#153]
版本：20.04LTS
iso：ubuntukylin-ukui3.0-20200320-amd64.iso
测试环境：联想启天M415-N000台式机
测试步骤：
1.桌面存在多个文件，左键多选几个文件
2.右键对多选的文件进行操作

预期结果： 右键可以对多选的全部文件进行操作
实际结果：左键选中多个，右键只能选中一个文件进行操作。文件管理器同样的操作，右键可以操作多个文件

**Comment by MeganHemh** [comment]
我本地最新版本是可以的，本周集成新版本可以验证一下。

**Comment by Yue-Lan** [comment]
42af2690f6556b8c57310a10500e3c1e85b4a989 修复了这个问题

**Comment by 1216338727aa** [comment]
20200328版本测试通过。
