### ISSUE TITLE
桌面新创建文件，会被任务栏遮挡

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#154]
![2020-03-27 11-07-23屏幕截图](https://user-images.githubusercontent.com/48200161/77717439-71915800-701b-11ea-8def-d96b0ffbc8a6.png)

**Comment by Yue-Lan** [comment]
桌面视图的大小是由屏幕的可用区域动态决定的，如果可用区域异常，则桌面视图的区域也会异常。。。

这一块还需要@hepuyao的协助，使得任务栏的区域和屏幕不可用区域实现一一对应

**Comment by MeganHemh** [comment]
最新版本可用区域正常，不会出现被遮挡的情况。

**Comment by 1216338727aa** [comment]
20200611 test  passed
