### ISSUE TITLE
Rename file's prefix name have unexcepted behaviour

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#156]
Distribution: `Ubuntu Kylin`
Build version: `daily`
Architecture: `amd64`

__Reproduce__
First, choose a target file which have non-null prefix and suffix name.
Then, rename prefix name to null, press `Enter` confirm it. The target file will be hidden in current directory.

__Excepted__
This behaviour should be invalid

**Comment by Yue-Lan** [comment]
这不是一个bug，桌面不会显示以半角点号开头的文件，因为它们在逻辑上被认为是隐藏文件。。。

要查看隐藏的文件，可以在文件管理器中通过ctrl+H进行查看

**Comment by xiaodongliu-nudt** [comment]
@Yue-Lan @liumin0322 应该重命名时增加判断，不可以为空。

**Comment by MeganHemh** [comment]
1. 重命名为空或者特殊的“.” ".."文件名无效，继续保留原名称。
2. 修改为.doc等以点开头的文件名，会被认为是隐藏文件，正常情况看不到。
修改已经提交，本周新集成的版本可验证。

**Comment by liumin0322** [comment]
20200402-beta版本测试未通过。
1、将文件名称全部删除为空时，提示信息为：移动文件xxx时出错：文件已存在。提示信息不正确
2、新建文件.doc重命名时删除.doc前的文字，应仍被保存为原文件名。

**Comment by MeganHemh** [comment]
上次桌面部分忘了修改，已经按照要求都作了修改，本周新版本可验证。

**Comment by vhtq18w** [comment]
如果我确实想这样重命名以隐藏文件了. 是否在用户确认之后, 允许这种行为会更好.

**Comment by liumin0322** [comment]
Tested pass in the 20200410 version
