### ISSUE TITLE
Can not free memory  after accessed a directory with a large number of files

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#159]
Distribution: `Ubuntu Kylin`
Build version: `daily`
Architecture: `amd64`

__Reproduce__
First, open a directory with a large number of files, such as `/usr/share/icons/`.
Then `Peony` will use more than `1-2 GB` memory. Sometime it will __CRASH__.
And after you quit `Peony`, the memory can not auto free.

**Comment by Yue-Lan** [comment]
> **Reproduce**
> First, open a directory with a large number of files, such as `/usr/share/icons/`.
> Then `Peony` will use more than `1-2 GB` memory. Sometime it will **CRASH**.

I have refactored the thumbnail frameworks, it should not appear.

> And after you quit `Peony`, the memory can not auto free.

The latest commit resolve this problem.

**Comment by 1216338727aa** [comment]
20200528 test passed
