### ISSUE TITLE
通过拖动文件至U盘中，文件不是被复制，而是移动

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#16]
By dragging the file to the USB drive, the file is not copied, but moved

**Comment by Yue-Lan** [comment]
Usually drag and drop means 'move' in peony... Maybe I should add an dialog for asking user which operation should be executed when native move is not supported.

**Comment by Yue-Lan** [comment]
The latest commit 39dad89ae6e7a9103975cf75a704eee72a5dc47a resolved this problem.

**Comment by liumin0322** [comment]
20200302测试通过
