### ISSUE TITLE
在列表试图的状态下，打开图片文件夹，设置为图标试图后无法显示缩略图

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#161]
![2020-03-31 17-47-29屏幕截图](https://user-images.githubusercontent.com/48200161/78012565-ba2c7680-7377-11ea-9e51-be2703dba9d0.png)

**Comment by Yue-Lan** [comment]
这是一个bug，之前为解决了修改listview排序卡顿的问题将model设置为了消极响应状态。。。

我会尽快修复这个bug

**Comment by 1216338727aa** [comment]
20200402版本测试通过
