### ISSUE TITLE
The file name next to file which are unzipped is displayed incorrectly

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#162]
Distribution: `Ubuntu Kylin`
Build version: `daily`
Architecture: `amd64`

__Reproduce__
Select some archive files to extract, the file name next to extracting file will dispalyed incorrect name.

![2020-03-31 21-18-25屏幕截图](https://user-images.githubusercontent.com/48200161/78031197-cf180280-7395-11ea-8228-e768d2494a70.png)

__Excepted__
Show correct name.

**Comment by MeganHemh** [comment]
解压的时候生成了新文件，会放到前面，文件列表刷新存在一定问题。

**Comment by MeganHemh** [comment]
已修改提交，下个版本可验证。

**Comment by 1216338727aa** [comment]
20200604 test passed
