### ISSUE TITLE
[multilingual] The 12-hour date format displays incorrect Chinese information

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#164]
Distribution: `Ubuntu Kylin`
Build version: `daily`
Architecture: `amd64`

__Reproduce__
In the file's detailed information widget, some create or modified date information that use 12-hour date format displays have incorrect Chinese information.

![Screenshot from 2020-04-03 15-53-06](https://user-images.githubusercontent.com/48200161/78337383-7b8afc00-75c3-11ea-9fb6-6328cbc9fe7a.png)

__Excepted__
Its correctly display system language.

**Comment by MeganHemh** [comment]
英文版本存在的问题，需要改为am/pm.

**Comment by MeganHemh** [comment]
看了一下，目前是直接转化为系统时间的，需要确认是否是因为切换语言后，系统时间未切换翻译造成的。

**Comment by MeganHemh** [comment]
Have fixed this issue and commited, please have a check in next version release.

**Comment by 1216338727aa** [comment]
The 20200508 version passed the test
