### ISSUE TITLE
Some right-click menu options don't have correct selectable status

### ISSUE THREAD

**Issue by Luchangcheng-nudt** [ukui/peony#165]
Distribution: `Ubuntu Kylin`
Build version: `daily`
Architecture: `amd64`

__Reproduce__
Open a folder without write permission, right-click the blank area and select the option to `create a new file` / `create a directory`. These options are selectable.

__Excepted__
These options are not selectable。

**Comment by Yue-Lan** [comment]
这是一个bug，创建操作的错误没有被正确的处理。

peony的设计逻辑是错误处理在操作开始之后，这样能够减少预处理带来的开销。对于创建文件失败的操作我会以弹窗的形式进行处理。

**Comment by 1216338727aa** [comment]
The 20200410 version passed the test
