### ISSUE TITLE
[dark theme] the minimize, maximize and close button have low UI recognition in dark theme

### ISSUE THREAD

**Issue by Luchangcheng-nudt** [ukui/peony#167]
Distribution: `Ubuntu Kylin`
Build version: `daily`
Architecture: `amd64`

**Comment by Yue-Lan** [comment]
peony尝试使用ukui-styles提供的特殊协议实现图标的高亮效果，请确保peony，qt5-styles-ukui，以及ubuntkylintheme的版本是目前最新版本

**Comment by Luchangcheng-nudt** [comment]
> peony尝试使用ukui-styles提供的特殊协议实现图标的高亮效果，请确保peony，qt5-styles-ukui，以及ubuntkylintheme的版本是目前最新版本
确实是最新版本

![2020-04-04 14-35-56屏幕截图](https://user-images.githubusercontent.com/29215152/78420511-57dabb00-7682-11ea-965c-edd3dfc06510.png)
![2020-04-04 14-37-37屏幕截图](https://user-images.githubusercontent.com/29215152/78420514-62955000-7682-11ea-8b63-1b3717215e3e.png)

**Comment by Yue-Lan** [comment]
已确认现有版本确实存在问题，最新的提交应该修复了这个问题，请在下一个版本继续验证并更新状态

**Comment by 1216338727aa** [comment]
The 20200410 version passed the test
