### ISSUE TITLE
[icons] the icons of desktop can not display when dual-screen use mirror mode

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#168]
Distribution: `Ubuntu Kylin`
Build version: `daily`
Architecture: `amd64`

__Reproduce__

Connected a secondary monitor, change the display mode to `mirror`. Then the icons on desktop will disappeared.

![2020-04-04 16-58-23屏幕截图](https://user-images.githubusercontent.com/48200161/78423068-53b89880-7696-11ea-81b3-1df125fcea2e.png)

**Comment by Yue-Lan** [comment]
是我的失误。。。之前遇到并且处理过这个问题，只是最近的重构忘记处理这个问题了，我会尽快修复它

**Comment by Yue-Lan** [comment]
1ccafbbefa600ee3db1be3d15eb9b304034192bf 解决了这个问题

**Comment by liumin0322** [comment]
Tested pass in the 20200410 version
