### ISSUE TITLE
[high-resolution] the size of the window opened on high-resolution screen by default is abnormal

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#169]
Distribution: `Ubuntu Kylin`
Build version: `daily`
Architecture: `amd64`
Machine: `Huawei Matebook Pro X`

After installed on Huawei Matebook laptop device, the scale of file icons are abnormal.

![image](https://user-images.githubusercontent.com/16852919/78779962-76b5b600-79d0-11ea-98b6-3d78f9399798.png)

The display resolution of this device: `3000x2000`(pixel).

**Comment by Yue-Lan** [comment]
可能和当前设备的屏幕像素比(device pixel ratio)有关。。。应该是一个逻辑错误

现在的窗口默认尺寸和屏幕的分辨率和像素比都相关，可能去掉像素比就会恢复正常

**Comment by liumin0322** [comment]
test passed in the 20200418
