### ISSUE TITLE
dpkg-buildpackage编译失败

### ISSUE THREAD

**Issue by moshengrenzenme** [ukui/peony#17]
dh_missing: warning: usr/share/peony-qt/peony-qt_zh_CN.ts exists in debian/tmp but is not installed to anywhere
dh_missing: warning: usr/share/peony-qt/peony-qt_zh_CN.qm exists in debian/tmp but is not installed to anywhere
dh_missing: warning: usr/share/libpeony-qt/libpeony-qt_zh_CN.qm exists in debian/tmp but is not installed to anywhere
dh_missing: warning: usr/share/libpeony-qt/libpeony-qt_zh_CN.ts exists in debian/tmp but is not installed to anywhere
dh_missing: warning: usr/share/peony-qt-desktop/peony-qt-desktop_zh_CN.ts exists in debian/tmp but is not installed to anywhere
dh_missing: warning: usr/share/peony-qt-desktop/peony-qt-desktop_zh_CN.qm exists in debian/tmp but is not installed to anywhere
dh_missing: warning: usr/share/applications/peony.desktop exists in debian/tmp but is not installed to anywhere
	The following debhelper tools have reported what they installed (with files per package)
	 * dh_install: libpeony-dev (77), libpeony2 (5), peony (4), peony-common (6)
	 * dh_installdocs: libpeony-dev (0), libpeony2 (0), peony (0), peony-common (0)
	 * dh_installman: libpeony-dev (0), libpeony2 (0), peony (0), peony-common (2)
	If the missing files are installed by another tool, please file a bug against it.
	When filing the report, if the tool is not part of debhelper itself, please reference the
	"Logging helpers and dh_missing" section from the "PROGRAMMING" guide for debhelper (10.6.3+).
	  (in the debhelper package: /usr/share/doc/debhelper/PROGRAMMING.gz)
	Be sure to test with dpkg-buildpackage -A/-B as the results may vary when only a subset is built
	For a short-term work-around: Add the files to debian/not-installed
   dh_dwz
   dh_strip
   dh_makeshlibs
dpkg-gensymbols: 警告: some new symbols appeared in the symbols file: see diff output below
dpkg-gensymbols: 错误: some symbols or patterns disappeared in the symbols file: see diff output below
dpkg-gensymbols: 警告: debian/libpeony2/DEBIAN/symbols doesn't match completely debian/libpeony2.symbols
--- debian/libpeony2.symbols (libpeony2_2.0.0-1_amd64)
+++ dpkg-gensymbolsGXN4Yo	2020-02-19 17:28:45.136950029 +0800
@@ -1052,7 +1052,8 @@
  _ZN5Peony18FileOperationUtils35leftNameIsDuplicatedFileOfRightNameERK7QStringS3_@Base 2.0.0
  _ZN5Peony18FileOperationUtils4copyERK11QStringListRK7QStringb@Base 2.0.0
  _ZN5Peony18FileOperationUtils4linkERK7QStringS3_b@Base 2.0.0
- _ZN5Peony18FileOperationUtils4moveERK11QStringListRK7QStringb@Base 2.0.0
+#MISSING: 2.0.0-1# _ZN5Peony18FileOperationUtils4moveERK11QStringListRK7QStringb@Base 2.0.0
+ _ZN5Peony18FileOperationUtils4moveERK11QStringListRK7QStringbb@Base 2.0.0-1
  _ZN5Peony18FileOperationUtils5trashERK11QStringListb@Base 2.0.0
  _ZN5Peony18FileOperationUtils6createERK7QStringS3_NS_23CreateTemplateOperation4TypeE@Base 2.0.0
  _ZN5Peony18FileOperationUtils6removeERK11QStringList@Base 2.0.0
dh_makeshlibs: error: failing due to earlier errors
make: *** [debian/rules:6：binary] 错误 1
dpkg-buildpackage: 错误: debian/rules binary subprocess returned exit status 2

**Comment by Yue-Lan** [comment]
由于peony对外提供libpeony2，根据debian入库的规定，如果一个项目提供lib，则必须要有正确的symbol文件。这个问题发生的原因是API发生变化以后symbol没有来得及更新，如果是本地边包的话可以删掉debian/libpeony2.symbol以后再进行dpkg-buildpackage。

**Comment by moshengrenzenme** [comment]
> 由于peony对外提供libpeony2，根据debian入库的规定，如果一个项目提供lib，则必须要有正确的symbol文件。这个问题发生的原因是API发生变化以后symbol没有来得及更新，如果是本地边包的话可以删掉debian/libpeony2.symbol以后再进行dpkg-buildpackage。

最新版的代码已经可以通过了
