### ISSUE TITLE
When deleting desktop files, there will be overlapping desktop file icons, right-click refresh peony-qt-desktop crash

### ISSUE THREAD

**Issue by 1216338727aa** [ukui/peony#172]
Version: 20.04LTS
Iso: ubuntukylin-ukui3.0-20200410-amd64.iso
Test environment: Lenovo Qitian M415-N000 desktop
Test steps:
1. Delete desktop files
2.
Expected result: No abnormalities on the desktop
Actual result: When deleting desktop files, desktop file icons overlap, right-click refresh peony-qt-desktop crash
![图片](https://user-images.githubusercontent.com/39893452/79088187-6f95fb80-7d74-11ea-96f5-1d50eadddf30.png)

**Comment by Yue-Lan** [comment]
f602185f59aad664419842377a36b389e0446d05 might resolve that problem.

**Comment by 1216338727aa** [comment]
20200521 test passed
