### ISSUE TITLE
Peony-Mouse over "x" icon and display "最大化"

### ISSUE THREAD

**Issue by 1216338727aa** [ukui/peony#173]
Version: 20.04LTS
Iso: ubuntukylin-ukui3.0-20200410-amd64.iso
Test environment: Lenovo Qitian M415-N000 desktop
Test steps:
1. Open the file manager
2. Mouse over [X] icon
Expected result: display closed
Actual result: Chinese mode is “最大化”, English mode is close

**Comment by xiaodongliu-nudt** [comment]
There is something wrong with the prompt. When hovering over the “Maximization” button, there is no prompt in both English and Chinese enviorment.

**Comment by MeganHemh** [comment]
已经修改提交6ff4092827b66cc34a186e06a0f8300bb18aa9e1。
本周新集成版本可验证。

**Comment by 1216338727aa** [comment]
20200417 version passed the test
