### ISSUE TITLE
【customer feedback】  The right-click menu on the desktop cannot create new files such as wps type

### ISSUE THREAD

**Issue by Liang-zy** [ukui/peony#180]

**Comment by CrossCC** [comment]
After upgrading WPS to the official version of 11.1.0.9505-release, there is a template in the "template" directory in the user's home directory. Right-click to create a new wps related file. Does the default WPS software version need to be updated

**Comment by MeganHemh** [comment]
系统集成已添加模板，最新版本可创建了。

**Comment by Liang-zy** [comment]
20200702 test failed
