### ISSUE TITLE
The desktop is displayed as an open app in the taskbar

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#181]
![截图-2020年5月15日 16时48分32秒](https://user-images.githubusercontent.com/48200161/82031688-d472a780-96cc-11ea-863a-568ba8e35013.png)

**Comment by MeganHemh** [comment]
已经修改提交，新集成版本可验证。

**Comment by CrossCC** [comment]
http://pm2.kylin.com/zentao/bug-view-4208.html
