### ISSUE TITLE
Excel, PPT format files have small icons on the desktop

### ISSUE THREAD

**Issue by CrossCC** [ukui/peony#187]
Version：20.04LTS
ISO：ubuntukylin-20.04-050803-amd64.iso
Test environment：Lenovo ThinkPad-X1-Yoga、Lenovo Thinkpad-T430i

Test steps:
Create new Excel, PPT, Word, PDF documents, or copy these four documents to the desktop

Desired result:
Commonly used files, the icons on the desktop display the same size

actual results:
Excel and PPT documents have smaller icons on the desktop
![桌面图标对比](https://user-images.githubusercontent.com/33095911/82307987-bae69e00-99f3-11ea-8b57-4c3b51e0775a.png)

**Comment by CrossCC** [comment]
> Version：20.04LTS
> ISO：ubuntukylin-20.04-050803-amd64.iso
> Test environment：Lenovo ThinkPad-X1-Yoga、Lenovo Thinkpad-T430i
> 
> Test steps:
> Create new Excel, PPT, Word, PDF documents, or copy these four documents to the desktop
> 
> Desired result:
> Commonly used files, the icons on the desktop display the same size
> 
> actual results:
> Excel and PPT documents have smaller icons on the desktop
> ![桌面图标对比](https://user-images.githubusercontent.com/33095911/82307987-bae69e00-99f3-11ea-8b57-4c3b51e0775a.png)

测试步骤：
新建Excel、PPT、Word、PDF文档，或者拷贝这四种文档到桌面

期望结果：
常用的文件，在桌面的图标显示大小一致

实际结果：
Excel、PPT类的文档在桌面的图标较小
![桌面图标对比](https://user-images.githubusercontent.com/33095911/82308102-e5d0f200-99f3-11ea-8d11-2e5aedd89dd9.png)

**Comment by Yue-Lan** [comment]
Please transfer this issue to ubuntukylin-theme.

**Comment by CrossCC** [comment]
The problem has been transferred
