### ISSUE TITLE
File manager starts automatically and has incorrect function,The taskbar preview shows "desktop",Click the black screen

### ISSUE THREAD

**Issue by ikeyhzj** [ukui/peony#188]
Version: V10
Test environment: lenovo ZHAOXIN KaiTianS620Z-D410

**Comment by ikeyhzj** [comment]
![20200520_204759](https://user-images.githubusercontent.com/22652111/82447828-64ed2580-9adb-11ea-83ff-55d72f565628.jpg)
![20200520_204811](https://user-images.githubusercontent.com/22652111/82447838-69b1d980-9adb-11ea-8fad-c595d8795e26.jpg)

**Comment by Yue-Lan** [comment]
resolved with 0b2b0202cf494a476cafdd09952a22df16914fd0.

**Comment by ikeyhzj** [comment]
0521 version test failed

**Comment by MeganHemh** [comment]
duplicated with #181

**Comment by MeganHemh** [comment]
已经修改提交，新集成版本可验证。

**Comment by CrossCC** [comment]
http://pm2.kylin.com/zentao/bug-view-4208.html
