### ISSUE TITLE
When the icon is reduced, it turns black.

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#196]
缩小图标后，图标变为黑色
![2020-05-22 17-15-34屏幕截图](https://user-images.githubusercontent.com/48200161/82652337-0a290a80-9c50-11ea-9fe2-917ac5d1dd2e.png)

**Comment by Yue-Lan** [comment]
Please transfer this issue to ubuntukylin-themes.

**Comment by CrossCC** [comment]
http://pm2.kylin.com/zentao/bug-view-4243.html
