### ISSUE TITLE
File Manager slides to the bottom with a blank line

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#198]
文件管理器滑至最底部有一行空白
![2020-05-23 11-27-34屏幕截图](https://user-images.githubusercontent.com/48200161/82722514-18cbfc00-9cfa-11ea-845b-a0b4e6124b83.png)

**Comment by MeganHemh** [comment]
为解决文件名比较长，在最下面一行时显示不全做的修改，是否参照win10系统，文件名过长时，显示部分名字以及省略号？

**Comment by CrossCC** [comment]
http://pm2.kylin.com/zentao/bug-view-4212.html
