### ISSUE TITLE
No flash drive name displayed

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#199]
不显示U盘名称
![2020-05-23 13-35-08屏幕截图](https://user-images.githubusercontent.com/48200161/82722604-cc34f080-9cfa-11ea-9583-7f0d8438ce50.png)

**Comment by MeganHemh** [comment]
下个版本会同步过去，新版本可验证。

**Comment by CrossCC** [comment]
http://pm2.kylin.com/zentao/bug-view-4211.html
