### ISSUE TITLE
安装deb报错

### ISSUE THREAD

**Issue by lizhuangs** [ukui/peony#200]
系统deepin15.11，安装https://packages.debian.org/unstable/peony这个链接的amd版本报错，
请问有什么好的解决办法的？
```
正在选中未选择的软件包 peony。
(正在读取数据库 ... 系统当前共安装有 235698 个文件和目录。)
正准备解包 peony_2.1.2-1_amd64.deb  ...
正在解包 peony (2.1.2-1) ...
dpkg: 依赖关系问题使得 peony 的配置工作不能继续：
 peony 依赖于 libgcc-s1 (>= 3.0)；然而：
  未安装软件包 libgcc-s1。
 peony 依赖于 libpeony2 (= 2.1.2-1)；然而：
  未安装软件包 libpeony2。
 peony 依赖于 libqt5core5a (>= 5.12.2)；然而：
系统中 libqt5core5a:amd64 的版本为 5.7.1+dfsg-10deepin。
 peony 依赖于 libqt5gui5 (>= 5.11.0~rc1) | libqt5gui5-gles (>= 5.11.0~rc1)；然而：
系统中 libqt5gui5:amd64 的版本为 5.7.1+dfsg-10deepin。
  未安装软件包 libqt5gui5-gles。
 peony 依赖于 libqt5widgets5 (>= 5.11.0~rc1)；然而：
系统中 libqt5widgets5:amd64 的版本为 5.7.1+dfsg-10deepin。
 peony 依赖于 qtbase-abi-5-12-5；然而：
  未安装软件包 qtbase-abi-5-12-5。
 peony 依赖于 peony-common (= 2.1.2-1)；然而：
  未安装软件包 peony-common。

dpkg: 处理软件包 peony (--install)时出错：
 依赖关系问题 - 仍未被配置
正在处理用于 lastore-daemon (0.14.6-1+comsta) 的触发器 ...
正在处理用于 desktop-file-utils (0.23-1) 的触发器 ...
正在处理用于 bamfdaemon (0.5.3-2) 的触发器 ...
Rebuilding /usr/share/applications/bamf-2.index...
正在处理用于 mime-support (3.60) 的触发器 ...
在处理时有错误发生：
 peony
```

**Comment by Yue-Lan** [comment]
按照readme文档，安装好相关的依赖（以peony的debian/control中的Build-Depends字段为准），手动编译安装即可

**Comment by lizhuangs** [comment]
我看了下readme中的要求qt-default最低要求5.12，但是我的安装后是5.7。我看了下qt官方的开发包1.3G。有什么办法不用安装官方包升级qt版本的。

**Comment by Yue-Lan** [comment]
readme上面的文档没有来得及更新，现在peony可以支持qt5.6及以上版本了。目前文档有些地方确实会有误导，我找个时间更新一下文档:D

**Comment by lizhuangs** [comment]
但是为什么安装报错里面显示的也是需要5.12.2以上呢。。。
```
 peony 依赖于 libqt5core5a (>= 5.12.2)；然而：
系统中 libqt5core5a:amd64 的版本为 5.7.1+dfsg-10deepin。
```

**Comment by Yue-Lan** [comment]
可能和debian/control有关，如果编译没问题的话可以直接sudo make install/uninstall装上去，终端运行peony看看跑不跑得起来

**Comment by moshengrenzenme** [comment]
@lizhuangs 可以自己解包然后修改依赖字段，或者是强制安装忽略依赖

**Comment by lizhuangs** [comment]
make也会报错的，我在另一个issue里面已经说了。我手动安装这些依赖包，安装到了libqtcore5a这里就不行了，和系统的冲突了。。

**Comment by Yue-Lan** [comment]
如果系统有对应的包作为替代的话应该就可以，看#201的报错，你可能需要试着装一下libkf5windowsystem-dev

**Comment by lizhuangs** [comment]
> libkf5windowsystem-dev

感谢，我试了下那一步通过了，然后报错
```
../../src/windows/main-window.cpp:28:44: fatal error: private/qwidgetresizehandler_p.h: 没有那个文件或目录
 #include <private/qwidgetresizehandler_p.h>
                                            ^
compilation terminated.
Makefile:603: recipe for target 'main-window.o' failed
make[1]: *** [main-window.o] Error 1
make[1]: Leaving directory '/home/tudou/peony/build/src'
Makefile:44: recipe for target 'sub-src-make_first' failed
make: *** [sub-src-make_first] Error 2
```

**Comment by Yue-Lan** [comment]
缺少qt private api的头文件，需要安装qtbase5-private-dev这个包

**Comment by lizhuangs** [comment]
> 缺少qt private api的头文件，需要安装qtbase5-private-dev这个包

非常感谢，已经成功安装了！我建议在readme上添加这些依赖说明。
另外我安装后的界面非常的土，和我在演示视频中看到的那种半透明效果区别很大。
尤其是顶部的菜单看起来是一个个的方块，类似以前xp的窗体。
是否还有什么没有安装，不会是需要安装peony-qt-desktop 替换我现在的桌面吧？

**Comment by lizhuangs** [comment]
中文说明推荐安装qt5-gtk2-platformtheme，但是这个deb我安装报上面的libqt5core5a那个错。个人感觉是缺少gtk主题。
![1](https://user-images.githubusercontent.com/7904121/82791578-97629e00-9ea0-11ea-8ea6-7bb50ea2168f.png)

**Comment by Yue-Lan** [comment]
gtk2也是过时的主题了，可以试试qt5-ukui-platformtheme，不过在deepin15.11上可能不太好使用ukui的主题，同样需要手动编译和安装，可以先试一试用kde的breeze或者oxygen。

安装主题之后，可以终端输入peony --style=主题名，选择不同的主题

**Comment by lizhuangs** [comment]
> gtk2也是过时的主题了，可以试试qt5-ukui-platformtheme，不过在deepin15.11上可能不太好使用ukui的主题，同样需要手动编译和安装，可以先试一试用kde的breeze或者oxygen。
> 
> 安装主题之后，可以终端输入peony --style=主题名，选择不同的主题

试一下那个qt5-ukui-platformtheme，没有使用文档，根据页面说明生成文档还报错了。。。
我用peony --style=主题名，主题名我选择的是我系统本身的/usr/share/themes/下面的名字。
不过没有生效，可能里面的主题不是GTK无法识别。

**Comment by Yue-Lan** [comment]
> 试一下那个qt5-ukui-platformtheme，没有使用文档，根据页面说明生成文档还报错了。。。

关于安装和使用，readme上面没有讲太细，具体可以参考项目wiki

> 我用peony --style=主题名，主题名我选择的是我系统本身的/usr/share/themes/下面的名字。
不过没有生效，可能里面的主题不是GTK无法识别。

qt主题和gtk不一样，要使用gtk主题，首先得安装qt5-gtk2-platformtheme，然后peony --style=gtk2。

qt应用的gtk主题切换需要借助系统的设置才能进行，我不太清楚deepin15.11具体如何设置。

如果想要一个能够配置qt主题的图形工具，qt5ct是一个选择，它能够列出系统中已安装或默认集成的qt主题。

**Comment by lizhuangs** [comment]
主题太折腾了，感谢解惑。
