### ISSUE TITLE
File type read error after copying an ISO file

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#203]
复制iso文件，图标显示为文本文件，且焦点始终显示在副本文件上
![2020-05-25 14-34-33屏幕截图](https://user-images.githubusercontent.com/48200161/82785282-e30f4a80-9e94-11ea-808a-18a24eda2a94.png)

**Comment by MeganHemh** [comment]
最新版本已经OK, 可验证。

**Comment by liumin0322** [comment]
test passed
