### ISSUE TITLE
Parallel replication not implemented

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#204]
![2020-05-25 14-32-10屏幕截图](https://user-images.githubusercontent.com/48200161/82785838-f4a52200-9e95-11ea-961a-1afe8222fb1d.png)

**Comment by MeganHemh** [comment]
兰悦已添加并行操作支持，需要才工具栏菜单勾选"并行操作"。6.15号版本做同步后可验证。
代码提交号： 62a8b483af7dd572cf3151cfefc537398187a8e1

**Comment by CrossCC** [comment]
http://pm2.kylin.com/zentao/bug-view-4209.html
