### ISSUE TITLE
右键文件夹没有压缩或者使用...打开

### ISSUE THREAD

**Issue by lizhuangs** [ukui/peony#205]
系统deepin15.11，右键文件夹发现没有压缩功能。
然后也没有使用xxx打开的功能，比如vs code。
看起来似乎右键相关的功能还没有完善？
这些都是常用的功能，没有这个使用起来体验大打折扣。
因为我个人是普通使用者，喜欢界面操作。
不知道是不是因为我的系统不是麒麟所以不支持？

**Comment by Yue-Lan** [comment]
peony不直接提供压缩功能，需要安装parchives插件，所有的插件都放在peony-extensions项目下

文件夹的右键打开方式可以加上，感谢反馈

**Comment by MeganHemh** [comment]
压缩功能装了插件就OK, 文件夹选中后右键有在“新标签中打开”或者“新窗口中打开选项”。

**Comment by lizhuangs** [comment]
> 压缩功能装了插件就OK, 文件夹选中后右键有在“新标签中打开”或者“新窗口中打开选项”。

压缩功能已经好了。右键我指的是使用xxx软件打开，比如在vs code打开文件夹，我在其它文件管理器中是有这个功能的。

**Comment by 1216338727aa** [comment]
20200604 test passed
