### ISSUE TITLE
路径导航栏不能复制

### ISSUE THREAD

**Issue by lizhuangs** [ukui/peony#206]
1、路径导航栏存在多级时，不能右键任何一级复制路径，实际使用中经常会复制路径，现在路径上面右键是没有反应的。
2、鼠标移动到路径后面，进入编辑模式，此时路径最前面显示出file://,不知道是出于什么考虑要加上file://，因为这样我全选复制出来的路径前面就会多了file://，我用过很多文件管理器默认前面是没有这个的，仅仅在windows浏览器打开本地文件会有这种情况。
所以对于现在的使用来说，想复制某个路径，只能进入编辑模式，复制file://后面的操作？
我建议缺省默认就是file://不要显示出来，另外在路径导航上面添加右键复制功能，这样可以复制任意一级路径非常方便。

**Comment by Yue-Lan** [comment]
感谢反馈，地址栏还目前确实体验不佳，这些建议对我们很有帮助

**Comment by MeganHemh** [comment]
右键复制路径功能已经添加，默认不显示file:后续再考虑优化。

**Comment by 1216338727aa** [comment]
20200611  test passed
