### ISSUE TITLE
选中文件或文件夹会有一个小方块一样的东西

### ISSUE THREAD

**Issue by lizhuangs** [ukui/peony#207]
1、选中文件夹就可以看到这个，有net的n和e之间
2、选中文件夹后，鼠标点一下其它地方，也可以看到，但是截图的时候看不到了，看起来似乎是悬浮在上面的一个什么东东。
如下所示：
![2](https://user-images.githubusercontent.com/7904121/82859253-cf252080-9f48-11ea-9568-f03b266c4c64.png)

**Comment by Yue-Lan** [comment]
这是一个focus rect…有一些主题有，有一些没有

focus rect理应是在文本周围绘制的，只是现在的视图我改过，没有完全按照主题的规范来，所以出现了这个问题…

**Comment by 1216338727aa** [comment]
20200604 test passed
