### ISSUE TITLE
Change the view to, list view, create a new folder or file, right click to refresh, the file disappears

### ISSUE THREAD

**Issue by 1216338727aa** [ukui/peony#212]
![image](https://user-images.githubusercontent.com/39893452/83989101-e8ca5d00-a977-11ea-8820-e7467a03cd24.png)

**Comment by MeganHemh** [comment]
兰悦已经修改提交：de5eca6d0bb1ec1e4f0041cb1df9d74d706f19ec
本周如果有新版本集成可验证。

**Comment by 1216338727aa** [comment]
20200618 test passed
