### ISSUE TITLE
File manager, click search, continuous search in search box, cancel search, overlapping search box fonts

### ISSUE THREAD

**Issue by 1216338727aa** [ukui/peony#219]
Search for "aaaa" in the search box and press enter
Search again "bbbbbb" multiple times to cancel the search

![image](https://user-images.githubusercontent.com/39893452/84493241-09791680-acda-11ea-9298-800b67678a6d.png)

**Comment by MeganHemh** [comment]
问题原因：搜索时生成的按钮未添加到列表，没清理到。
已修改提交，本周有新版本可验证。

**Comment by 1216338727aa** [comment]
20200618  test passed
