### ISSUE TITLE
【customer feedback】 There is no mounted partition in "Computer", the partition cannot be mounted using "Enter" key

### ISSUE THREAD

**Issue by Liang-zy** [ukui/peony#226]
![image](https://user-images.githubusercontent.com/39893452/85274891-25d33b00-b4b2-11ea-8f4c-fea22246def7.png)

**Comment by Yue-Lan** [comment]
https://github.com/ukui/peony-extensions/commit/354b6fa46ac84e0e3da8f9a09f8fbeede7d25831

**Comment by Liang-zy** [comment]
20200702 test passed
