### ISSUE TITLE
文件拷贝过程中，点击取消按钮，文件不会显示未拷贝完成

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#23]
Click the Cancel button during the file copying process, the file will not be displayed without being copied

**Comment by xiaodongliu-nudt** [comment]
This is a bug. The unfinished copy should be deleted after clicking the cancel button, but now it is still there.

**Comment by Yue-Lan** [comment]
> This is a bug. The unfinished copy should be deleted after clicking the cancel button, but now it is still there.

@xiaodongliu-nudt In fact, copy or move operation will rollback when it was cancelled as my expected. If it doesn't, could you provide me more detials?

I think @liumin0322  means it should have a dialog to tell user that the operation is not finished and would be rollbacked when we cancel an operation here, then everything will be same with current process. So I set the low priotry and enhancement label for this issue.

If an operation really was not be rollbacked, It is better to create a new issue for that bug.

Cheers.

**Comment by xiaodongliu-nudt** [comment]
Duplicated with issue 89, so this bug is closed.
