### ISSUE TITLE
conky窗口，鼠标点击后，转移到peony-qt-desktop下面

### ISSUE THREAD

**Issue by handsome-feng** [ukui/peony#233]
https://www.ubuntukylin.com/ukylin/forum.php?mod=viewthread&tid=193236 
conky窗口，鼠标点击消失，转移到peony-qt-desktop窗口下面，peony-qt-desktop没有设置为置于最底层窗口吗？

**Comment by Yue-Lan** [comment]
桌面并不是简单的置底，NETWM有专门规则的来指示窗口如何绘制，和其它桌面应用窗口不同，conky和peony-qt-desktop的窗口类型都是“桌面”，所以窗口管理器在混成时不能确定谁应该在底部。

**Comment by handsome-feng** [comment]
OK，不清楚Ubuntu那边默认怎么处理的，先修改conky的window type吧：
$ conky -C > ~/.conkyrc
然后修改~/.conkyrc里的window-type这一行，将desktop改成dock:
own_window_type = 'desktop',
改为：
own_window_type='dock',
