### ISSUE TITLE
多次执行文件拷贝和删除操作后，终端通过ls命令，可查看到大量空文件，右键刷新也可查看到这些文件闪现

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#27]
After repeatedly performing file copy and delete operations, the terminal can view a large number of empty files through the ls command, and you can also view these files by right-clicking and refreshing

**Comment by MeganHemh** [comment]
最新版本试了，没有出现该问题。

**Comment by 1216338727aa** [comment]
20200611 test passed
