### ISSUE TITLE
Desktop file right click to rename, has no effect.

### ISSUE THREAD

**Issue by MeganHemh** [ukui/peony#325]
After install a new system,  create a new folder, right click it to rename, then failed.

重现步骤
[前置条件]

[硬件环境]

联想M425-n000台式机

[软件环境]

[概率]

100%

[步骤]

1.在桌面新建一个文件夹；

2.右键选择“重命名”

[结果]

2.重命名失败，仅选中此文件
[期望]

2.重命名成功

**Comment by MeganHemh** [comment]
禅道 bug id : 15426, 20.04.1版本，07.31号发布。

**Comment by MeganHemh** [comment]
最新版本OK

**Comment by liumin0322** [comment]
20200818 test passed
