### ISSUE TITLE
Use print screen key, save picture in  desktop, or create a new file in desktop, other picture disappear.

### ISSUE THREAD

**Issue by MeganHemh** [ukui/peony#326]
After install a new system will appear,  after a while it will be normal. 07.31 Version of 20.04.1.
重现步骤
[前置条件]

桌面已有图片或文件

[硬件环境]

联想M425-n000台式机

[软件环境]

[概率]

100%

[步骤]

1.安装系统后使用快捷键“print screen”截图保存在桌面；

2.在桌面新建一个文件

[结果]

1.桌面显示刚保存的图片，桌面已有的其他图标消失

2.桌面不显示新建的文件（但文件管理器里面可以看到），在桌面刷新后概率性可以显示出来；

[期望]

1.桌面显示刚保存的图片，桌面已有的其他图标正常显示

2.桌面显示新建的文件及其他已存在的图片及文件

**Comment by MeganHemh** [comment]
禅道 15308.

**Comment by Yue-Lan** [comment]
0805没有复现，需要确认

**Comment by MeganHemh** [comment]
桌面重构后已经OK.

**Comment by liumin0322** [comment]
20200818 test passed
