### ISSUE TITLE
 BUG #15533 【桌面】排序不规则的图标，注销再登陆后会自动排序

### ISSUE THREAD

**Issue by MeganHemh** [ukui/peony#328]
重现步骤
[步骤]

1、在桌面新建文件或者文件夹

2、打乱文件在桌面的顺序，随意放置

3、注销再登陆用户

[结果]

概率性的出现 打乱的文件按顺序排列，刷新后恢复

[期望]

**Comment by Yue-Lan** [comment]
有可能是因为登陆时桌面频繁resize导致刷新后图标又恢复qlistview的默认排列，https://github.com/ukui/peony/commit/f9a6a26f3af85b22ba72549203c0c0ef33705f70 可能对解决这个问题有帮助。

**Comment by Liang-zy** [comment]
20.04.1 test passed
