### ISSUE TITLE
The modified time of the new template document is incorrect

### ISSUE THREAD

**Issue by Liang-zy** [ukui/peony#330]
Version: 20.04 LTS
Test environment: ThinkPad X1
Test steps:
Step 1. Open the file manager
Step 2. Right click to create a new document
Expected results:
Step 1. Open the file manager
Step 2. Creating a new file is normal
actual results:
Step 1. Normal
Step 2. When creating a new file (such as doc, docx, ppt, pptx, xls, xlsx), the creation date and time are displayed incorrectly
![image](https://user-images.githubusercontent.com/39893452/89377414-51d61300-d724-11ea-82bf-4d23a5127b81.png)

**Comment by Yue-Lan** [comment]
Maybe I need changed the modified time manually for template files.

**Comment by Yue-Lan** [comment]
I remember that 15915825de9eff5376865505f6563a50ce378d98 resolved the problem somehow. You might have to test and confirm at latest release.

**Comment by Liang-zy** [comment]
20.04.1 test passed
