### ISSUE TITLE
Right-click the recycle bin to create a new file or folder error

### ISSUE THREAD

**Issue by Liang-zy** [ukui/peony#331]
Version: 20.04 LTS
Test environment: ThinkPad X1
Test steps:
Step 1. Desktop-Open Recycle Bin
Step 2. Right-click menu-new file or folder
Expected results:
Step 1. Open the Recycle Bin
Step 2. The recycle bin cannot create new files or folders
actual results:
Step 1. Normal
Step 2. The recycle bin can create new files or folders with the right-click menu, but it will prompt ‘file operation error’. The recycle bin’s right-click creation function should be grayed out or blocked.
![image](https://user-images.githubusercontent.com/39893452/89381756-3838c980-d72c-11ea-8686-4e03bc9811e7.png)

**Comment by Yue-Lan** [comment]
We are not going to fix this problem until we refactor the file operations error handling frameworks.

**Comment by Liang-zy** [comment]
20.04.1 test passed
