### ISSUE TITLE
Right-click the folder properties, the close button disappears

### ISSUE THREAD

**Issue by Liang-zy** [ukui/peony#333]
Version: 20.04 LTS
Test environment: ThinkPad X1
Test steps:
Step 1. Right click on the folder-Properties
Step 2. Right click on the "X Close" button
Expected results:
Step 1. Open the properties interface
Step 2. Right-click the close button should be unresponsive
actual results:
Step 1. Open the properties interface
Step 2. Right-click the close button, a check box will pop up, click the check box, and then the close button disappears
![image](https://user-images.githubusercontent.com/39893452/89484845-fe220300-d7d1-11ea-9fd1-0bc4f67a3af6.png)

**Comment by MeganHemh** [comment]
Resolved in commit 72f780c951451c812481dc65bc288298c7124b0f

**Comment by Liang-zy** [comment]
20.04.1  test passed
