### ISSUE TITLE
执行多个拷贝和删除操作后，桌面卡死

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#35]
Desktop crashes after multiple copy and delete operations

**Comment by MeganHemh** [comment]
最新版本已经稳定，频繁文件操作不会出现卡死或者崩溃问题。

**Comment by 1216338727aa** [comment]
20200618 test  faild

**Comment by Yue-Lan** [comment]
能否使用gdb运行桌面然后复现这个bug？我希望能看到崩溃时的堆栈信息

**Comment by Liang-zy** [comment]
20200702 test passed
