### ISSUE TITLE
桌面上除计算机、回收站、主文件夹外，选中所有新创建文件，按delete键后，桌面显示为空

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#42]
Except for computer, recycle bin, and home folder on the desktop, select all newly created files and press delete. The desktop is empty

**Comment by Yue-Lan** [comment]
Not a bug.

**Comment by Yue-Lan** [comment]
Please updating to the latest version then confirm if the problem is resolved.

**Comment by liumin0322** [comment]
2.0.1-3~20200221版本测试通过
