### ISSUE TITLE
桌面右键设置壁纸，打开的为主目录文件夹

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#44]
Right-click on the desktop to set the wallpaper and open the home directory folder

**Comment by xiaodongliu-nudt** [comment]
@Yue-Lan @MeganHemh Since we have the “Wallpaper settings” function in the control center, and the current GUI of "Right-click Wallpaper settings" is rather awful, could we now just hide the "Right-click Wallpaper settings" option？

**Comment by Yue-Lan** [comment]
Yes. @MeganHemh Could you help me handle this simple problem?

**Comment by MeganHemh** [comment]
When clicked this menu, directly  go to control center set background page.

**Comment by 1216338727aa** [comment]
20200320版本 桌面右键设置壁纸无反应
