### ISSUE TITLE
deepin20启动报错Settings schema 'org.ukui.style' is not installed

### ISSUE THREAD

**Issue by lizhuangs** [ukui/peony#440]
deepin20启动报错
Settings schema 'org.ukui.style' is not installed

另外deepin20编译也报错，需要安装以下3个：
sudo apt install libudisks2-dev
sudo apt install libnotify-dev
sudo apt install libcanberra-dev

**Comment by handsome-feng** [comment]
你好，第一个问题已经解决了，感谢反馈！

编译报错的问题，需要先安装编译依赖，写在debian/control文件里了，可以 sudo mk-build-deps -i peony/debian/control（control文件路径）一键安装

**Comment by lizhuangs** [comment]
问题是我sudo mk-build-deps -i peony/debian/control后，这个问题依然存在，是哪里不对吗？

**Comment by lizhuangs** [comment]
`tudou@tudou-Deepin:/data/workspace/opensource$ sudo mk-build-deps -i peony/debian/control
dh_testdir
dh_testroot
dh_prep
dh_testdir
dh_testroot
dh_install
dh_installdocs
dh_installchangelogs
dh_compress
dh_fixperms
dh_installdeb
dh_gencontrol
dh_md5sums
dh_builddeb
dpkg-deb: 正在 '../peony-build-deps_3.0.3-1_all.deb' 中构建软件包 'peony-build-deps'。

The package has been created.
Attention, the package has been created in the current directory,
not in ".." as indicated by the message above!
(正在读取数据库 ... 系统当前共安装有 342541 个文件和目录。)
准备解压 peony-build-deps_3.0.3-1_all.deb  ...
正在解压 peony-build-deps (3.0.3-1) 并覆盖 (3.0.3-1) ...
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
Starting pkgProblemResolver with broken count: 0
Starting 2 pkgProblemResolver with broken count: 0
Done
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
有 1 个软件包没有被完全安装或卸载。
解压缩后会消耗 0 B 的额外空间。
正在设置 peony-build-deps (3.0.3-1) ...
tudou@tudou-Deepin:/data/workspace/opensource$ /usr/bin/peony

(process:26309): GLib-GIO-ERROR **: 09:55:20.663: Settings schema 'org.ukui.style' is not installed
追踪与中断点陷阱`

**Comment by lizhuangs** [comment]
生成了一个包peony-build-deps_3.0.3-1_all.deb，我看了下是安装成功的。另外我特意重新pull了一下最新的代码，试了下还是这样。

**Comment by lizhuangs** [comment]
已解决，我整个项目重新build后，就好了，感谢。另外建议更新一新说明文档，我每次下载最新的下来编译，没有一次是成功的。。。。

**Comment by handsome-feng** [comment]
好的，：）
