### ISSUE TITLE
桌面图标有时只显示计算机、kylin，有时只显示回收站、kylin

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#46]
Desktop icons sometimes only display computers, kylin, sometimes only recycle bin, kylin

**Comment by MeganHemh** [comment]
兰悦修改之后，我做了20次注销操作，5次重启计算机，中间还做了复制文件以及移动图标位置等操作，都正常显示。更新版本后可验证。

**Comment by MeganHemh** [comment]
Cccured once in Lan-Yue's computer, still need to be fixed.

**Comment by Yue-Lan** [comment]
I will try to fix this issue.

**Comment by Yue-Lan** [comment]
I almost not met this case after I limit the refresh frequncy. So I turned the emergency from high to low.

**Comment by 1216338727aa** [comment]
20200521 test passed
