### ISSUE TITLE
Desktop icons are set to oversize, , and some file names are not displayed completely

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#57]
桌面设置为超大图标，部分文件的文件名显示不完全

测试步骤：
1、桌面右键-视图类型-超大图标
2、可查看到部分word文档、excel表格、PDF文档、压缩文件等文件名显示不完全

**Comment by MeganHemh** [comment]
Duplicated with #37 ,only when long name icon in the bottom row will reappear this bug.

**Comment by liumin0322** [comment]
PDF格式的较长文件名，显示不完全

**Comment by MeganHemh** [comment]
最新版本已解决，除非是在最下面一排被任务栏遮挡的情况(有其他issue).
本周最新版本可进行验证。

**Comment by liumin0322** [comment]
20200402-beta版本测试通过，最下面一排存在被任务栏遮挡的情况(有其他issue).
