### ISSUE TITLE
建议：增加退格键的快捷键

### ISSUE THREAD

**Issue by moshengrenzenme** [ukui/peony#58]
增加一个退格键的快捷键，功能是返回上层目录

**Comment by MeganHemh** [comment]
昨天晚上提交的代码，没有集成到本周的版本，下周的版本可进行验证。

**Comment by enjoyuruf** [comment]
返回上层目录后，不会选中返回前的目录。在文件夹较多的目录中切换相邻目录需要反复重新寻找位置。
建议增设在返回上层目录，选中返回前目录功能。
