### ISSUE TITLE
建议：磁盘的分区名称不要用硬盘序列号

### ISSUE THREAD

**Issue by moshengrenzenme** [ukui/peony#59]
磁盘的分区名称不要用硬盘序列号，因为侧边栏比较窄，最后边的磁盘大小基本看不到，和没有效果差不多，可以使用卷标，如果没有卷标可以使用分区的大小来显示，主要是没人看序列号这个东西，如果是用来区分硬盘的话，我宁可使用设备号，比如sda，sdb加上卷标或者大小来显示，短小精悍

**Comment by MeganHemh** [comment]
最新版本兰悦已经修改提交了，本周新集成版本可验证。

**Comment by 1216338727aa** [comment]
20200402版本测试通过
