### ISSUE TITLE
快捷键是否可以加一个说明的页面

### ISSUE THREAD

**Issue by moshengrenzenme** [ukui/peony#6]
快捷键如果有改动的话希望可以加一个说明的地方，要不然不知道是如何使用的，还可以按照习惯，把f2改成重命名，另外，文件管理的帮助里，有一个小节，重命名的时候，文档写的还是f2重命名，希望能统一一下

**Comment by Yue-Lan** [comment]
说明不准确确实是问题，关于重命名快捷键的问题我会尽快修复，不过帮助文档是另外的项目，可能需要转交这个issue。

**Comment by MeganHemh** [comment]
快捷键的说面页面，最好让设计师根据设计规范出一个设计，做出来的效果会好一些。

**Comment by MeganHemh** [comment]
f2重命名的功能已经支持，设计师已经决定快捷键说明会在控制面板统一做。
