### ISSUE TITLE
Computer, Trash, and Kylin folders failed to rename

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#61]
计算机、回收站和kylin文件夹重命名失败

测试步骤：
1、左键慢速点击3次计算机、回收站和kylin文件夹
2、文件名处可进行重命名
3、修改文件名称失败

**Comment by MeganHemh** [comment]
Not allow to change these names,  fix code commited.

**Comment by liumin0322** [comment]
20200320测试通过
