### ISSUE TITLE
列表模式下，第一次刷新，会跳转到根目录下

### ISSUE THREAD

**Issue by CrossCC** [ukui/peony#63]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-2020022402-amd64.iso
测试环境：兆芯E台式机

测试步骤：

1. 打开任意有多文件或文件夹的文件夹。
2. 点击右键刷新。

预期结果：文件夹重新加载，显示该文件夹中的内容。

实际结果：第一次刷新后会跳转到文件系统目录，即根目录。概率性出现在根目录文件管理器卡死的情况。

**Comment by MeganHemh** [comment]
Commited fix code, can check it in a new version test.

**Comment by liumin0322** [comment]
20200320测试通过
