### ISSUE TITLE
新建文件时一闪而过文件可以重命名的状态

### ISSUE THREAD

**Issue by CrossCC** [ukui/peony#64]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-2020022402-amd64.iso
测试环境：兆芯E台式机

测试步骤：
1. 在文件夹中右键新建文件或文件夹

预期结果：可以直接重命名。或者直接创建成功，需手动重命名。

实际结果：点击新建文件后，新文件的名可以修改，但一闪而过，不能直接重命名。可以修改为手动确认初始文件名，或直接确定文件名，手动重命名

**Comment by liumin0322** [comment]
20200320测试通过
