### ISSUE TITLE
文件夹的共享不能勾选

### ISSUE THREAD

**Issue by CrossCC** [ukui/peony#66]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-2020022402-amd64.iso
测试环境：兆芯E台式机

测试步骤：
1. 右键点击文件夹，属性
2. 共享，勾选共享文件夹

预期结果：文件夹可以共享。

实际结果：共享文件夹的勾选框勾选不上。

**Comment by Yue-Lan** [comment]
请确认Samba是否正常运作

**Comment by CrossCC** [comment]
@Yue-Lan  系统默认没有安装samba，也没有该服务。手动安装Samba之后，共享文件夹可以勾选了。

**Comment by MeganHemh** [comment]
2004默认集成了samba，可以勾选了。

**Comment by 1216338727aa** [comment]
20200508 version test failed

**Comment by MeganHemh** [comment]
已将samba添加为share插件依赖项，有安装成功共享插件则肯定可以勾选。
下个集成版本可验证。

**Comment by 1216338727aa** [comment]
20200521 test passed
