### ISSUE TITLE
若重命名是文件名重复，错误提示重复

### ISSUE THREAD

**Issue by CrossCC** [ukui/peony#67]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-2020022402-amd64.iso
测试环境：兆芯E台式机

测试步骤：
1. 新建文件命名为test
2. 再新建文件页命名为test

预期结果：提示该文件名已存在。

实际结果：
会弹出三个错误提示框
1. 操作正忙：在执行该操作之前有操作未完成，它需要等待上一个操作完成后再执行。
2. 文件操作错误，提示文件已存在，可以点击忽略或者取消。
3. 第三个提示和第二个提示相同。

因为有两个相同的错误提示，所有才会有操作正忙的错误信息。

**Comment by CrossCC** [comment]
![错误信息1](https://user-images.githubusercontent.com/33095911/75437404-1b37e780-5991-11ea-842d-87405174e086.jpg)

![错误信息2](https://user-images.githubusercontent.com/33095911/75437420-1f640500-5991-11ea-9c21-5b7cf80a7d44.jpg)

**Comment by Yue-Lan** [comment]
resolved with commit 018b33a10e2f018f2fa1d71f6a8754725e1f6019

**Comment by liumin0322** [comment]
提示信息错误，不是移动文件
![2020-03-02 20-29-27屏幕截图](https://user-images.githubusercontent.com/48200161/75677069-8f41fa80-5cc5-11ea-9de8-5c956739eeb0.png)

**Comment by xiaodongliu-nudt** [comment]
首先，提示信息有误。另外，当前忽略和取消两个按钮操作结果一样，都是按照。按道理创建新文件重名时，弹出错误框，

**Comment by Yue-Lan** [comment]
目前文件操作框架的设计存在先天缺陷，需要重构文件操作框架才能很好的解决这个问题

**Comment by liumin0322** [comment]
20200818 test passed
