### ISSUE TITLE
通过gio set设置metadata::emblems属性后角标无法展示

### ISSUE THREAD

**Issue by hh0518** [ukui/peony#680]
用的麒麟V10-SP1-2203系统，通过gio set或者gvfs-set-attribute设置“metadata::custom-icons”能正确设置并显示自定义图标，但是“metadata::custom-icons”虽然能设置上，但是角标却无法展示。

**Comment by hh0518** [comment]
peony已经升级到最新的v3.2.3，同样也不能展示角标。

**Comment by xlango** [comment]
请问你是怎么解决这个问题的？能提供一下设置角标的方案吗？

**Comment by wupf-code** [comment]
请问是怎么解决这个问题的？
