### ISSUE TITLE
create file then change file content. close file and file size is not update.

### ISSUE THREAD

**Issue by dou-y** [ukui/peony#69]
When I create a new file and put some content in it.

![截屏2020-03-0214 56 35](https://user-images.githubusercontent.com/59866026/75652537-4888dc00-5c96-11ea-8f29-daaa1e72faa9.jpg)
its size still show 0.
![截屏2020-03-0214 57 50](https://user-images.githubusercontent.com/59866026/75652566-58082500-5c96-11ea-949e-51e523590f63.jpg)
only manual click “refresh” show its actually size.
![截屏2020-03-0214 58 03](https://user-images.githubusercontent.com/59866026/75652627-7c640180-5c96-11ea-89f9-32da9b4d0601.jpg)

**Comment by liumin0322** [comment]
20200309版本测试通过
