### ISSUE TITLE
开机之后文件管理不是静默启动

### ISSUE THREAD

**Issue by moshengrenzenme** [ukui/peony#7]
开机之后文件管理不是静默启动，会直接出现在桌面打开一个窗口

**Comment by Yue-Lan** [comment]
文件管理器和桌面启动程序应该已经分开了，按道理来说不会有弹窗的情况。。。可能是更新之后与session manager组件之间的交互出了问题，需要确认。

**Comment by xiaodongliu-nudt** [comment]
Duplicated issue, closed.
