### ISSUE TITLE
文件夹右键菜单的快捷键问题

### ISSUE THREAD

**Issue by CrossCC** [ukui/peony#72]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-2020022402-amd64.iso
测试环境：兆芯E台式机、兆芯E笔记本、联想T490

存在问题：
1. 在新窗口打开和新建的快捷键重复
2. 属性快捷键无效

**Comment by MeganHemh** [comment]
根据UKUI3.0整理的规范， Ctrl + N 为打开新窗口快捷键， Ctrl + Shift +N为新建文件夹快捷键，Alt + Enter在选中目标情况下显示属性。

**Comment by liumin0322** [comment]
20200314版本测试通过
