### ISSUE TITLE
在文件管理器中，选择“修改时间排序”并重命名文件后，文件排序恢复

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#76]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200302-amd64.iso
测试环境：联想台式机

测试步骤：
1、打开文件管理器
2、右键选择按照“修改时间排序”
3、对其中一个文件进行重命名

预期结果：重命名后，文件排序不会刷新

实际结果：重命名后，文件排序又刷新到“文件名称排序”状态

**Comment by MeganHemh** [comment]
已修改提交，本周新集成增強版本可验证。

**Comment by 1216338727aa** [comment]
20200402版本测试通过
