### ISSUE TITLE
将文件拖动到桌面文件，提示文件操作错误，是否需要覆盖

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#77]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200302-amd64.iso
测试环境：联想台式机
测试步骤：
1、拖动文件至桌面文件重合后，松开鼠标左键

预期结果：无法触发文件焦点

实际结果：提示文件操错误 --> 询问文件是否要覆盖

**Comment by 1216338727aa** [comment]
20200320测试通过
