### ISSUE TITLE
突然提示peony退出，桌面黑了

### ISSUE THREAD

**Issue by moshengrenzenme** [ukui/peony#8]
突然提示peony退出，桌面黑了，打开peony也不行，但觉像是接管桌面的那一部分退出了，但是没有被重新启动

**Comment by Yue-Lan** [comment]
桌面和peony分开了，试试peony-qt-desktop -w -d

**Comment by MeganHemh** [comment]
最新版本，桌面和文件管理器都稳定了。

**Comment by Liang-zy** [comment]
20200702 test passed
