### ISSUE TITLE
打开多个图片文件夹后，内存耗尽，文件管理器闪退

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#80]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200302-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开图片缩略图，并打开多个存放图片的文件夹
2、打开系统监视器，可查看到内存耗尽

预期结果：显示正常

实际结果：内存耗尽，文件管理器闪退

**Comment by Yue-Lan** [comment]
目前的缩略图框架存在缺陷，它以无损的方式读取和展示数据，所以非常耗费资源。

你可以勾选选项->禁用缩略图，这样将避免这个问题，我会尽快改进缩略图框架。

**Comment by Yue-Lan** [comment]
虽然处理了缩略图无损格式的问题，但是生成缩略图的这一段时间可能还是会导致内存临时飙升。。。

我会尝试限制生成缩略图的线程数量，降低缩略图内存占用的峰值

**Comment by vhtq18w** [comment]
多个 pdf 的缩略图会不会这个现象更严重

**Comment by Yue-Lan** [comment]
> 多个 pdf 的缩略图会不会这个现象更严重

导致这个bug的最主要原因是线程没有受控制，一些极端操作可能会造成内存的疯涨

图像有损缩放+限制线程数的方式可以解决这些问题，只是现在线程控制这一块有点麻烦。。。

我想在原来的基础上加上信号量机制达到一个比较可控的效果，但是目前的问题在于现在路径跳转时没有一个取消线程的机制，这样会导致如果在处理大量图片时进行路径跳转到另一个有图片的目录的话，需要等待之前的图片处理完成才能进入正常的流程，这明显是不合理的

要增加取消机制，也许还需要一个全局的uri-watcher的hash表用来指导这些线程是否需要真正被执行

**Comment by Yue-Lan** [comment]
> > 多个 pdf 的缩略图会不会这个现象更严重
> 
> 导致这个bug的最主要原因是线程没有受控制，一些极端操作可能会造成内存的疯涨
> 
> 图像有损缩放+限制线程数的方式可以解决这些问题，只是现在线程控制这一块有点麻烦。。。
> 
> 我想在原来的基础上加上信号量机制达到一个比较可控的效果，但是目前的问题在于现在路径跳转时没有一个取消线程的机制，这样会导致如果在处理大量图片时进行路径跳转到另一个有图片的目录的话，需要等待之前的图片处理完成才能进入正常的流程，这明显是不合理的
> 
> 要增加取消机制，也许还需要一个全局的uri-watcher的hash表用来指导这些线程是否需要真正被执行

1463780f9368a31084209bf1d5b33cb0626ec7e5 重构了缩略图执行的代码，对缩略图的线程做了严格的控制

闪退的问题可能不能简单的和缩略图问题绑定起来，因为有可能在缩略图生成期间有其它操作，不能排除其它因素导致的闪退。。。建议验证之后修改issue的标题，以免在我标记resovled的时候引起歧义

如果能够找到闪退的必现步骤，重新提出一个issue是最恰当的

**Comment by liumin0322** [comment]
20200328版本测试通过。
