### ISSUE TITLE
桌面右键选择“以管理员身份打开目录”，弹出无法获取系统主题警告

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#87]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200302-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、桌面右键选择“以管理员身份打开目录”

预期结果：无报错，或隐藏该选项

实际结果：弹出无法获取系统主题警告

**Comment by MeganHemh** [comment]
Fixed and commited to git,  peony-admin plugin is not patched in version 2004LTS, so it will be updated after the 2004.
**Please check it after 2004.**

**Comment by MeganHemh** [comment]
Peony-admin plugin is not patched in 2004LTS, we will fix it after 2004LTS when give out the peony-admin plugin to users.

**Comment by liumin0322** [comment]
20200309版本测试通过，已屏蔽该选项
