### ISSUE TITLE
文件拷贝过程中，点击取消按钮，会有未完成的拷贝遗留

### ISSUE THREAD

**Issue by xiaodongliu-nudt** [ukui/peony#89]
版本：20200302
文件拷贝过程中（例如大文件），点击取消按钮，会有未完成的拷贝遗留（因为拷贝未完成，所以遗留文件的大小会小于原文件，但是这个文件理应被删除掉）

**Comment by Yue-Lan** [comment]
Confirmed.

**Comment by Yue-Lan** [comment]
fix the issue with commit 97c5b87230d02e685cb1ee696410744f6a52677f.

**Comment by liumin0322** [comment]
20200309版本测试通过
