### ISSUE TITLE
在新窗口中打开快捷键错误

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#90]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200302-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开文件管理器窗口
2、鼠标移至菜单栏第一个图标，可查看到悬浮提示：在新窗口中打开(W)
3、键盘执行Ctrl+W

预期结果：打开一个相同路径的新窗口

实际结果：当前窗口被关闭

**Comment by MeganHemh** [comment]
根据快捷键规范，Ctrl+N是打开新窗口，Ctrl+W关闭当前活动窗口。提示与功能已经修改一致，新版本可验证。

**Comment by liumin0322** [comment]
20200314版本测试通过
