### ISSUE TITLE
在桌面上单击文件，文件名动态向上移动

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#91]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200302-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、在桌面上，左键单击文件
2、可查看到文件名动态向上移动

预期结果：与文件管理器中效果一致

实际结果：可查看到文件名动态向上移动

**Comment by Yue-Lan** [comment]
f503c920220e78ec37b841d4857168940b4ab84f 修复了这个问题

**Comment by 1216338727aa** [comment]
20200328版本测试通过。
