### ISSUE TITLE
拷贝文件窗口中，部分地方显示异常

### ISSUE THREAD

**Issue by liumin0322** [ukui/peony#95]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200302-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、拷贝多个文件
2、查看拷贝文件窗口的显示

预期结果：显示正常

实际结果：“正常复制..."显示过小，“4中的第3个”建议修改为“正在复制4个文件中的第3个”

**Comment by Yue-Lan** [comment]
字体问题已经在主题框架中修复
